# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on: 
 push:
   branches: 
     - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package
    - name: echo
      run: ls
    - name: Deploy package
      run: mvn -X deploy -Dregistry=https://maven.pkg.github.com/h182675 -Dtoken=aee9c43f34dbff908896f39a9115bb7fe949ae8c
